name: Postman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file Back-end/pom.xml
        working-directory: Back-end

      - name: Set up Docker Compose
        run: |
          cd Back-end && docker-compose up -d
          # Wait for services to be ready
          sleep 30

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run ./src/postman/collection.json
        working-directory: Back-end

      - name: Stop Docker Compose
        if: always()
        run: cd Back-end && docker-compose down