name: Postman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: List directory structure
      run: |
        echo "Repository structure:"
        find . -type d -not -path "*/\.*" | sort
        echo "All pom.xml files:"
        find . -name "pom.xml" | sort
    
    - name: Build with Maven (skip tests)
      run: |
        cd Back-end
        mvn -B package -DskipTests
      
    - name: Set up Docker Compose
      uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./Back-end/docker-compose.yml"
        down-flags: "--volumes"
        services: |
          db
          redis
    
    - name: Wait for services to be ready
      run: sleep 30
      
    - name: Run Spring Boot tests with Docker services
      run: |
        cd Back-end
        # Override database connection parameters for tests
        mvn test -Dspring.datasource.url=jdbc:postgresql://localhost:5432/myshop -Dspring.datasource.username=postgres -Dspring.datasource.password=postgres
    
    - name: Install Newman
      run: npm install -g newman
    
    - name: Run Postman Tests
      run: |
        # List postman files to verify their location
        find . -path "*/postman/*.json" | sort
        
        # Run Newman with the correct path
        cd Back-end
        newman run ./src/postman/collection.json
