name: Postman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: List directory structure
      run: find . -type f -name "pom.xml" | sort
    
    - name: Build with Maven
      run: |
        # Adjust this path to wherever your pom.xml actually is
        cd Back-end
        mvn -B package
      
    - name: Set up Docker Compose
      uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./Back-end/docker-compose.yml"
        down-flags: "--volumes"
        services: |
          app
          db
          redis
    
    - name: Wait for services to be ready
      run: sleep 30
    
    - name: Install Newman
      run: npm install -g newman
    
    - name: Run Postman Tests
      run: |
        # List postman files to verify their location
        find . -path "*/postman/*.json" | sort
        
        # Run Newman with the correct path
        cd Back-end
        newman run ./src/postman/collection.json
